### ISSUE TITLE
libgladeWARNING console messages on startup

### ISSUE THREAD

**Issue by ghost** [sderaut/obmenux#5]
it starts and seems to function just fine, but i am getting error messages in the console when i start it:

```
[a@i obmenux-1.1.1]$ obmenux

(obmenux:6068): libglade-WARNING **: Error loading image: Failed to open file './mnu48.png': No such file or directory

(obmenux:6068): libglade-WARNING **: could not convert string to type `GdkPixbuf' for property `logo'
```

the number in the first part `(obmenux:6068)` changes every time i run it, so i think that is more related to processor id or something like that. but the rest of the message stays the same.

note: my last version of this program, when it was still called obmenu, and not obmenux, didn't have these warnings.

**Comment by sderaut** [comment]
This is one of those "works for me so maybe it works for everyone" issues. To fix it, I might have to limit the installation to using only one directory, and not being user-specific or distro-wide, so assuming that's /usr/local/share/obmenux for the glade file and the png files it looks for. Even that might not work, as far as I know, because the installer scripts might not put the glade file and the png files in the same directory. So it would help if I had some information: where the installer script you're using puts your mnu48.png file.

**Comment by ghost** [comment]
```
[a@i ~]$ sudo find / -name mnu48.png
/usr/share/obmenux/mnu48.png
/usr/share/obmenu/mnu48.png
/home/a/Desktop/267-obmenux/obmenux-master/obmenux-1.1.1/icons/mnu48.png
[a@i ~]$ 
```

**Comment by ghost** [comment]
working with Commit 267a85e0334d70fa5ea3850129448843a1d44017

i **don't** get the errors when i run it from `~/` or several other folders. but i **do** get the errors when i run it from where i installed it:

```
[a@i obmenux-1.1.1]$ obmenux

(obmenux:6375): libglade-WARNING **: Error loading image: Failed to open file './mnu48.png': No such file or directory

(obmenux:6375): libglade-WARNING **: could not convert string to type `GdkPixbuf' for property `logo'
[a@i obmenux-1.1.1]$ pwd
/home/a/Desktop/267-obmenux/obmenux-master/obmenux-1.1.1
```

**Comment by sderaut** [comment]
So I could try to fix it by hard-coding that path /usr/share/obmenux in the glade file, which would limit it to local but not user installations. I was just going to ask you if you were sure that you weren't running the executable uninstalled, because that will give you that sort of error. I could try to change the arrangement of folders in the install package so that it doesn't have a problem with that.

**Comment by ghost** [comment]
_installed_? i'm just running the program :)
wait... i thought i "installed" it when i ran `python2 setup.py install`
...but as for doing _more_ than that, no.

**Comment by sderaut** [comment]
I understand how it's getting the error. I just have to decide how to solve it so it will work best and in most situations doing the correct and expected thing. It's finding the glade file because that's in the working directory when you run it. When installing, the glade file and the icon files are put in the same directory, so that they work together, but in the installer (the way it's arranged in the repo) they're in different directories.

**Comment by sderaut** [comment]
So I moved the glade file to the same folder as the icons in the project directory. That way it will find the icons from the installer when you run it in the installer directory, and the icons installed when you run it anywhere else. That should be good for testing it and fiddling with it.
